#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include "macro.h"
#include "cJSON.h"

//Functions
static void writePermissions(cJSON *elAuthorized, cJSON *elLocalRanges, FILE *pfM) {
//ex: [ "_all_", "_dongle_", "_localnetwork_", "admin", "user1" ]
	int requireNb = 0;
	int firstTime = 1;
	cJSON *authorized = NULL;
	cJSON_ArrayForEach(authorized, elAuthorized) {
		char sz[256];
		if (strcmp(authorized->valuestring, "_all_") == 0) {
			char sz[] = "\t\tRequire all granted\n";
			fwrite(sz, strlen(sz), 1, pfM);
		} else if (strcmp(authorized->valuestring, "_dongle_") == 0) {
			char sz[] = "\t\tRequire local\n";
			fwrite(sz, strlen(sz), 1, pfM);
		} else if (strcmp(authorized->valuestring, "_localnetwork_") == 0) {
			cJSON *range = NULL;
			cJSON_ArrayForEach(range, elLocalRanges) {
				char sz[256];
				sprintf(sz, "\t\tRequire ip %s\n", range->valuestring);
				fwrite(sz, strlen(sz), 1, pfM);
			}
		} else {
			if (firstTime) {
				char sz[] = "\t\tRequire all granted\n";
				fwrite(sz, strlen(sz), 1, pfM);
				firstTime = 0;
			}
			char sz[256];
			sprintf(sz, "\t\tMyDongleCloudModuleAuthorized %s\n", authorized->valuestring);
			fwrite(sz, strlen(sz), 1, pfM);
			requireNb++;
		}
	}
	if (requireNb > 1) {
		char sz[] = "\t\tSatisfy any\n";
		fwrite(sz, strlen(sz), 1, pfM);
	}
}

static void writeSymlinks(int b, FILE *pfM) {
	char sz[256];
	sprintf(sz, "\t\tOptions %sFollowSymLinks\n", b ? "+" : "-");
	fwrite(sz, strlen(sz), 1, pfM);
}

static void writeIndexes(int b, FILE *pfM) {
	char sz[256];
	sprintf(sz, "\t\tOptions %sIndexes\n", b ? "+" : "-");
	fwrite(sz, strlen(sz), 1, pfM);
}

static void writeDirectoryIndex(char *s, FILE *pfM) {
	char sz[256];
	sprintf(sz, "\t\tDirectoryIndex %s\n", s);
	fwrite(sz, strlen(sz), 1, pfM);
}

static void writeLog(char *name, FILE *pfM) {
	char sz[256];
	sprintf(sz, "/disk/admin/.log/%s", name);
	mkdir(sz, 755);
	sprintf(sz, "\tCustomLog /disk/admin/.log/%s/web.log combined\n", name);
	fwrite(sz, strlen(sz), 1, pfM);
}

static void fillAlias_(cJSON *a, char *sub, cJSON *d, char *fqdn, char *tab, FILE *pfM) {
	if (d == NULL) {
		cJSON *iA = NULL;
		cJSON_ArrayForEach(iA, a) {
			char sz[256];
			sprintf(sz, "%sServerAlias %s.%s\n", tab, iA->valuestring, fqdn);
			fwrite(sz, strlen(sz), 1, pfM);
		}
	} else {
		cJSON *iD = NULL;
		cJSON_ArrayForEach(iD, d) {
			if (a == NULL) {
				char sz[256];
				sprintf(sz, "%sServerAlias %s%s%s\n", tab, sub, sub[0] ? "." : "", iD->valuestring);
				fwrite(sz, strlen(sz), 1, pfM);
			} else {
				cJSON *iA = NULL;
				cJSON_ArrayForEach(iA, a) {
					char sz[256];
					sprintf(sz, "%sServerAlias %s.%s\n", tab, iA->valuestring, iD->valuestring);
					fwrite(sz, strlen(sz), 1, pfM);
				}
			}
		}
	}
}

static void fillAlias(cJSON *elModule, cJSON *elModule2, cJSON *space, char *fqdn, int tabN, FILE *pfM) {
	cJSON *a = cJSON_GetObjectItem(elModule, "alias");
	cJSON *a2 = cJSON_GetObjectItem(elModule2, "alias");
	cJSON *d = cJSON_GetObjectItem(space, "domains");
	if (a)
		fillAlias_(a, NULL, NULL, fqdn, TAB(tabN), pfM);
	if (a2)
		fillAlias_(a2, NULL, NULL, fqdn, TAB(tabN), pfM);
	if (d) {
		if (strcmp(elModule->string, "Apache2") == 0)
			fillAlias_(NULL, "", d, NULL, TAB(tabN), pfM);
		else
			fillAlias_(NULL, elModule->string, d, NULL, TAB(tabN), pfM);
	}
	if (a)
		fillAlias_(a, NULL, d, NULL, TAB(tabN), pfM);
	if (a2)
		fillAlias_(a2, NULL, d, NULL, TAB(tabN), pfM);
}

void reloadApache2Conf() {
#ifndef DESKTOP
	PRINTF("Apache2: Reloading\n");
	system("sudo /usr/bin/systemctl reload apache2");
#endif
}

void buildApache2Conf(cJSON *modulesDefault, cJSON *modules, cJSON *space, char *fqdn) {
	PRINTF("Modules:Apache2: Enter\n");
#ifdef DESKTOP
	FILE *pfP = fopen("/tmp/ports.conf", "w");
#else
	FILE *pfP = fopen(ADMIN_PATH "Apache2/ports.conf", "w");
#endif
	char sz[2048];
	strcpy(sz, "\
Listen 80\n\
<IfModule ssl_module>\n\
	Listen 443\n\
</IfModule>\n");
	fwrite(sz, strlen(sz), 1, pfP);
#ifdef DESKTOP
	FILE *pfM = fopen("/tmp/main.conf", "w");
#else
	FILE *pfM = fopen(ADMIN_PATH "Apache2/main.conf", "w");
#endif
	strcpy(sz, "\
#This file is automatically generated and overwritten unless there is a boolean property\n\
#Apache2->overwrite: true in /disk/admin/.modules/MyDongleCloud/modules.json\n\n\
LoadModule mydonglecloud_module /usr/local/modules/Apache2/mod_mydonglecloud.so\n\
\n\
<Macro Macro_Redirect $1>\n\
	Alias /MyDongleCloud /usr/local/modules/Apache2/pages\n\
	<Directory /usr/local/modules/Apache2/pages>\n\
		Require all granted\n\
	</Directory>\n\
	ErrorDocument 401 /MyDongleCloud/unauthorized.php?m=$1\n\
	ProxyPass /MyDongleCloud/unauthorized.php !\n\
</Macro>\n\
<Macro Macro_SSL>\n\
	Include /usr/local/modules/Apache2/options-ssl-apache.conf\n\
	SSLCertificateFile /disk/admin/.modules/Apache2/fullchain.pem\n\
	SSLCertificateKeyFile /disk/admin/.modules/Apache2/privkey.pem\n\
</Macro>\n\n");
	fwrite(sz, strlen(sz), 1, pfM);
	cJSON *elLocalRanges = cJSON_GetObjectItem(cJSON_GetObjectItem(modulesDefault, "Apache2"), "localRanges");

	for (int i = 0; i < cJSON_GetArraySize(modulesDefault); i++) {
		cJSON *elModule = cJSON_GetArrayItem(modulesDefault, i);
		if (cJSON_HasObjectItem(elModule, "web")) {
			cJSON *elModule2 = cJSON_GetObjectItem(modules, elModule->string);
			char path[128];
			if (cJSON_HasObjectItem(elModule, "path"))
				strcpy(path, cJSON_GetStringValue2(elModule, "path"));
			else
				sprintf(path, "/usr/local/modules/%s", elModule->string);
			sprintf(sz, "\
<Macro Macro_%s>\n\
	MyDongleCloudModule %s\n\
	RewriteEngine On\n\
	Use Macro_Redirect %s\n", elModule->string, elModule->string, elModule->string);
			fwrite(sz, strlen(sz), 1, pfM);
			if (cJSON_HasObjectItem(elModule, "rewriteRule")) {
				sprintf(sz, "\t%s\n", cJSON_GetStringValue2(elModule, "rewriteRule"));
				fwrite(sz, strlen(sz), 1, pfM);
			}
			if (cJSON_HasObjectItem(elModule2, "rewriteRule")) {
				sprintf(sz, "\t%s\n", cJSON_GetStringValue2(elModule2, "rewriteRule"));
				fwrite(sz, strlen(sz), 1, pfM);
			}

			cJSON *elEnabled = cJSON_GetObjectItem(elModule, "enabled");
			if (cJSON_HasObjectItem(elModule2, "enabled"))
				elEnabled = cJSON_GetObjectItem(elModule2, "enabled");
			if (cJSON_IsTrue(elEnabled)) {
				cJSON *elAuthorized = cJSON_GetObjectItem(elModule, "authorized");
				if (cJSON_HasObjectItem(elModule2, "authorized"))
					elAuthorized = cJSON_GetObjectItem(elModule2, "authorized");

				if (cJSON_HasObjectItem(elModule, "reverseProxy")) {
					strcpy(sz, "\tProxyRequests Off\n\tProxyPreserveHost on\n\tProxyVia On\n");
					fwrite(sz, strlen(sz), 1, pfM);
					cJSON *elReverseProxy = cJSON_GetObjectItem(elModule, "reverseProxy");
					for (int j = 0; j < cJSON_GetArraySize(elReverseProxy); j++) {
						cJSON *elReverseProxy_ = cJSON_GetArrayItem(elReverseProxy, j);
						char *type_ = cJSON_GetStringValue2(elReverseProxy_, "type");
						char *path_ = cJSON_GetStringValue2(elReverseProxy_, "path");
						int reversePort = (int)cJSON_GetNumberValue(cJSON_GetObjectItem(elReverseProxy_, "port"));
						sprintf(sz, "\tProxyPass %s %s://localhost:%d%s\n\tProxyPassReverse %s %s://localhost:%d%s\n", path_, type_, reversePort, path_, path_, type_, reversePort, path_);
						fwrite(sz, strlen(sz), 1, pfM);
					}
					strcpy(sz, "\t<Proxy *>\n");
					fwrite(sz, strlen(sz), 1, pfM);
				} else {
					sprintf(sz, "\tDocumentRoot %s\n\t<Directory %s>\n", path, path);
					fwrite(sz, strlen(sz), 1, pfM);
				}
				if (cJSON_HasObjectItem(elModule, "addLineInDirectory")) {
					sprintf(sz, "\t\t%s\n", cJSON_GetStringValue2(elModule, "addLineInDirectory"));
					fwrite(sz, strlen(sz), 1, pfM);
				}
				if (cJSON_HasObjectItem(elModule2, "addLineInDirectory")) {
					sprintf(sz, "\t\t%s\n", cJSON_GetStringValue2(elModule2, "addLineInDirectory"));
					fwrite(sz, strlen(sz), 1, pfM);
				}
				writePermissions(elAuthorized, elLocalRanges, pfM);
				if (cJSON_HasObjectItem(elModule2, "DirectoryIndex"))
					writeDirectoryIndex(cJSON_GetStringValue2(elModule2, "DirectoryIndex"), pfM);
				else if (cJSON_HasObjectItem(elModule, "DirectoryIndex"))
					writeDirectoryIndex(cJSON_GetStringValue2(elModule, "DirectoryIndex"), pfM);
				if (cJSON_HasObjectItem(elModule2, "FollowSymLinks"))
					writeSymlinks(cJSON_IsTrue(cJSON_GetObjectItem(elModule2, "FollowSymLinks")), pfM);
				else if (cJSON_GetObjectItem(elModule, "FollowSymLinks"))
					writeSymlinks(cJSON_IsTrue(cJSON_GetObjectItem(elModule, "FollowSymLinks")), pfM);
				if (cJSON_HasObjectItem(elModule2, "Indexes"))
					writeIndexes(cJSON_IsTrue(cJSON_GetObjectItem(elModule2, "Indexes")), pfM);
				else if (cJSON_GetObjectItem(elModule, "Indexes"))
					writeIndexes(cJSON_IsTrue(cJSON_GetObjectItem(elModule, "Indexes")), pfM);

				if (cJSON_HasObjectItem(elModule, "reverseProxy"))
					strcpy(sz, "\t</Proxy>\n");
				else
					strcpy(sz, "\t</Directory>\n");
				fwrite(sz, strlen(sz), 1, pfM);
				if (cJSON_HasObjectItem(elModule, "addConfig")) {
					sprintf(sz, "%s\n", cJSON_GetStringValue2(elModule, "addConfig"));
					fwrite(sz, strlen(sz), 1, pfM);
				}
				if (cJSON_HasObjectItem(elModule2, "addConfig")) {
					sprintf(sz, "%s\n", cJSON_GetStringValue2(elModule2, "addConfig"));
					fwrite(sz, strlen(sz), 1, pfM);
				}
				if (strcmp(elModule->string, "Apache2") == 0) {
					for (int ii = 0; ii < cJSON_GetArraySize(modulesDefault); ii++) {
						cJSON *el_Module = cJSON_GetArrayItem(modulesDefault, ii);
						int localPort = (int)cJSON_GetNumberValue(cJSON_GetObjectItem(el_Module, "localPort"));
						sprintf(sz, "\
	RewriteCond %%{HTTP_HOST} ^(\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})$\n\
	RewriteRule ^/(MyDongleCloud|m)/%s.* %%{REQUEST_SCHEME}://%%{HTTP_HOST}:%d [NC,L]\n\
	RewriteRule ^/(MyDongleCloud|m)/%s.* %%{REQUEST_SCHEME}://%s.%%{HTTP_HOST} [NC,L]\n", el_Module->string, localPort, el_Module->string, el_Module->string);
						fwrite(sz, strlen(sz), 1, pfM);
					}
					strcpy(sz, "\n\
	ErrorDocument 404 /MyDongleCloud/notpresent.php\n\
	ErrorDocument 500 /MyDongleCloud/error.php\n\n");
					fwrite(sz, strlen(sz), 1, pfM);
				}
			} else {
				sprintf(sz, "\
	SSLProxyEngine On\n\
	RewriteCond %%{HTTP_HOST} ^(\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})(:\\d+)?$\n\
	RewriteRule ^/.*$ %%{REQUEST_SCHEME}://%%1/MyDongleCloud/disabled.php?m=%s [P,L]\n\
	RewriteRule ^/.*$ %%{REQUEST_SCHEME}://%s/MyDongleCloud/disabled.php?m=%s [P,L]\n\n", elModule->string, fqdn, elModule->string);
				fwrite(sz, strlen(sz), 1, pfM);
			}
			writeLog(elModule->string, pfM);
			sprintf(sz, "</Macro>\n");
			fwrite(sz, strlen(sz), 1, pfM);

			sprintf(sz, "<VirtualHost *:80>\n");
			fwrite(sz, strlen(sz), 1, pfM);
			if (fqdn != NULL) {
				if (strcmp(elModule->string, "Apache2") == 0)
					sprintf(sz, "\tServerName %s\n", fqdn);
				else
					sprintf(sz, "\tServerName %s.%s\n", elModule->string, fqdn);
				fwrite(sz, strlen(sz), 1, pfM);
				fillAlias(elModule, elModule2, space, fqdn, 1, pfM);
			}
			sprintf(sz, "\tUse Macro_%s\n</VirtualHost>\n", elModule->string);
			fwrite(sz, strlen(sz), 1, pfM);

			sprintf(sz, "<IfModule mod_ssl.c>\n\t<VirtualHost *:443>\n");
			fwrite(sz, strlen(sz), 1, pfM);
			if (fqdn != NULL) {
				if (strcmp(elModule->string, "Apache2") == 0)
					sprintf(sz, "\t\tServerName %s\n", fqdn);
				else
					sprintf(sz, "\t\tServerName %s.%s\n", elModule->string, fqdn);
				fwrite(sz, strlen(sz), 1, pfM);
				fillAlias(elModule, elModule2, space, fqdn, 2, pfM);
			}
			sprintf(sz, "\t\tUse Macro_%s\n\t\tUse Macro_SSL\n\t</VirtualHost>\n</IfModule>\n", elModule->string);
			fwrite(sz, strlen(sz), 1, pfM);
			int localPort = (int)cJSON_GetNumberValue(cJSON_GetObjectItem(elModule, "localPort"));
			if (localPort > 0) {
				sprintf(sz, "<VirtualHost *:%d>\n\tUse Macro_%s\n</VirtualHost>\n", localPort, elModule->string);
				fwrite(sz, strlen(sz), 1, pfM);
				sprintf(sz, "Listen %d\n", localPort);
				fwrite(sz, strlen(sz), 1, pfP);
			}
			strcpy(sz, "\n\n");
			fwrite(sz, strlen(sz), 1, pfM);
		}
	}
	fclose(pfP);
	fclose(pfM);
}
