#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include "macro.h"
#include "common.h"
#include "cJSON.h"
#include "json.h"
#include "base64.h"

//Functions
static void writePermissions(cJSON *elPermissions, cJSON *elLocalRanges, FILE *pfM) {
//Permissions: [ "_public_", "_dongle_", "_localnetwork_", "_groupadmin_", "_groupuser_", "admin", "user", ... ]
	int requireNb = 0;
	int firstTime = 1;
	cJSON *permission = NULL;
	cJSON_ArrayForEach(permission, elPermissions) {
		char sz[256];
		if (strcmp(permission->valuestring, "_public_") == 0) {
			char sz[] = "\t\tRequire all granted\n";
			fwrite(sz, strlen(sz), 1, pfM);
		} else if (strcmp(permission->valuestring, "_dongle_") == 0) {
			char sz[] = "\t\tRequire local\n";
			fwrite(sz, strlen(sz), 1, pfM);
		} else if (strcmp(permission->valuestring, "_localnetwork_") == 0) {
			cJSON *range = NULL;
			cJSON_ArrayForEach(range, elLocalRanges) {
				char sz[256];
				snprintf(sz, sizeof(sz), "\t\tRequire ip %s\n", range->valuestring);
				fwrite(sz, strlen(sz), 1, pfM);
			}
		} else {
			if (firstTime) {
				char sz[] = "\t\tRequire all granted\n";
				fwrite(sz, strlen(sz), 1, pfM);
				firstTime = 0;
			}
			char sz[256];
			snprintf(sz, sizeof(sz), "\t\tMyDongleCloudModulePermission %s\n", permission->valuestring);
			fwrite(sz, strlen(sz), 1, pfM);
		}
		requireNb++;
	}
	if (requireNb > 1) {
		char sz[] = "\t\tSatisfy any\n";
		fwrite(sz, strlen(sz), 1, pfM);
	}
}

static void writeSymlinks(int b, FILE *pfM) {
	char sz[256];
	sprintf(sz, "\t\tOptions %sFollowSymLinks\n", b ? "+" : "-");
	fwrite(sz, strlen(sz), 1, pfM);
}

static void writeIndexes(int b, FILE *pfM) {
	char sz[256];
	sprintf(sz, "\t\tOptions %sIndexes\n", b ? "+" : "-");
	fwrite(sz, strlen(sz), 1, pfM);
}

static void writeDirectoryIndex(char *s, FILE *pfM) {
	char sz[256];
	snprintf(sz, sizeof(sz), "\t\tDirectoryIndex %s\n", s);
	fwrite(sz, strlen(sz), 1, pfM);
}

static void writeLog(char *name, FILE *pfM) {
	char sz[256];
	snprintf(sz, sizeof(sz), "\tCustomLog /var/log/apache2/web-%s.log combined\n", name);
	fwrite(sz, strlen(sz), 1, pfM);
}


static void fillServer(int tabN, cJSON *elModule, cJSON *elModule2, cJSON *fqdn, FILE *pfM) {
	jsonPrintArray(tabN, "ServerName ", "ServerAlias ", strcmp(elModule->string, "apache2") == 0 ? "" : elModule->string, fqdn, "\n", pfM);
	cJSON *i = NULL;
	cJSON *a = NULL;
	a = cJSON_GetObjectItem(elModule, "alias");
	if (a)
		cJSON_ArrayForEach(i, a)
			jsonPrintArray(tabN, "ServerAlias ", "ServerAlias ",  i->valuestring, fqdn, "\n", pfM);
	a = cJSON_GetObjectItem(elModule2, "alias");
	if (a)
		cJSON_ArrayForEach(i, a)
			jsonPrintArray(tabN, "ServerAlias ", "ServerAlias ",  i->valuestring, fqdn, "\n", pfM);
}

void rewrite_(char *st, int port, FILE *pfM) {
	char sz[512];
	char port_[16];
	strcpy(port_, "");
	if (port > 0)
		sprintf(port_, ":%d", port);
	snprintf(sz, sizeof(sz), "\
	RewriteCond %%{HTTP_HOST} ^(\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})(:\\d+)?$\n\
	RewriteRule ^/m/%s.* %%{REQUEST_SCHEME}://%%1%s [NC,L]\n", st, port_);
	fwrite(sz, strlen(sz), 1, pfM);
}

void rewrite(cJSON *el_Module, cJSON *el_Module2, int port, FILE *pfM) {
	rewrite_(el_Module->string, port, pfM);
	cJSON *i = NULL;
	cJSON *a = NULL;
	a = cJSON_GetObjectItem(el_Module, "alias");
	if (a)
		cJSON_ArrayForEach(i, a)
			rewrite_(i->valuestring, port, pfM);
	a = cJSON_GetObjectItem(el_Module2, "alias");
	if (a)
		cJSON_ArrayForEach(i, a)
			rewrite_(i->valuestring, port, pfM);
}

void buildApache2Conf(cJSON *modulesDefault, cJSON *modules, cJSON *fqdn) {
	PRINTF("Modules:Apache2: Enter\n");
#ifdef DESKTOP
	FILE *pfP = fopen("/tmp/ports.conf", "w");
#else
	FILE *pfP = fopen(ADMIN_PATH "apache2/ports.conf", "w");
#endif
	char sz[2048];
	strcpy(sz, "\
<IfModule ssl_module>\n\
	Listen 443\n\
</IfModule>\n");
	fwrite(sz, strlen(sz), 1, pfP);
#ifdef DESKTOP
	FILE *pfM = fopen("/tmp/main.conf", "w");
#else
	FILE *pfM = fopen(ADMIN_PATH "apache2/main.conf", "w");
#endif
	cJSON *ap = cJSON_GetObjectItem(modulesDefault, "apache2");
	cJSON *ap2 = cJSON_GetObjectItem(modulesDefault, "apache2");
	cJSON *elLocalRanges = cJSON_GetObjectItem(ap, "localRanges");
	snprintf(sz, sizeof(sz), "\
#This file is automatically generated and overwritten unless there is a boolean property\n\
#Apache2->overwrite: true in /disk/admin/modules/_config_/_modules_.json\n\n\
LoadModule mydonglecloud_module /usr/local/modules/apache2/mod_mydonglecloud.so\n\
MyDongleCloudJwkPem /disk/admin/modules/betterauth/jwk-pub.pem\n\
LoadModule mydonglecloud_ip_module /usr/local/modules/apache2/mod_mydonglecloud_ip.so\n\
MyDongleCloudIPEnabled %s\n\
MyDongleCloudALEnabled %s\n\
\n\
<Macro Macro_Redirect $1>\n\
	RewriteEngine On\n\
	ProxyRequests Off\n\
	ProxyPreserveHost on\n\
	ProxyVia On\n\
	ProxyPass /_app_/auth/ http://localhost:8091/auth/\n\
	Alias /_app_ /usr/local/modules/apache2/pages\n\
	<Directory /usr/local/modules/apache2/pages>\n\
		Require all granted\n\
	</Directory>\n\
	ErrorDocument 401 /_app_/unauthorized.php?m=$1\n\
	ProxyPass /_app_/ !\n\
</Macro>\n\
<Macro Macro_SSL>\n\
	Include /usr/local/modules/apache2/options-ssl-apache.conf\n\
	SSLCertificateFile /disk/admin/modules/letsencrypt/fullchain.pem\n\
	SSLCertificateKeyFile /disk/admin/modules/letsencrypt/privkey.pem\n\
</Macro>\n", cJSON_IsTrue(cJSON_GetObjectItem(ap, "updateRemoteIP")) || cJSON_IsTrue(cJSON_GetObjectItem(ap2, "updateRemoteIP")) ? "on" : "off", cJSON_IsTrue(cJSON_GetObjectItem(ap, "autoLogin")) || cJSON_IsTrue(cJSON_GetObjectItem(ap, "autoLogin")) ? "on" : "off");
	fwrite(sz, strlen(sz), 1, pfM);
	strcpy(sz, "<Macro Macro_Rewrite>\n");
	fwrite(sz, strlen(sz), 1, pfM);
	for (int ii = 0; ii < cJSON_GetArraySize(modulesDefault); ii++) {
		cJSON *el_Module = cJSON_GetArrayItem(modulesDefault, ii);
		if (cJSON_HasObjectItem(el_Module, "web")) {
			cJSON *el_Module2 = cJSON_GetObjectItem(modules, el_Module->string);
			int localPort = (int)cJSON_GetNumberValue(cJSON_GetObjectItem(el_Module, "localPort"));
			rewrite(el_Module, el_Module2, localPort, pfM);
		}
	}
	strcpy(sz, "\
	RewriteCond %{HTTP_HOST} ^(app\\.)?(.*)\n\
	RewriteRule ^/m/([^/]+)(.*) %{REQUEST_SCHEME}://$1.%2$2 [NC,L]\n\
</Macro>\n\n\n");
	fwrite(sz, strlen(sz), 1, pfM);

	for (int i = 0; i < cJSON_GetArraySize(modulesDefault); i++) {
		cJSON *elModule = cJSON_GetArrayItem(modulesDefault, i);
		if (cJSON_HasObjectItem(elModule, "web")) {
			cJSON *elModule2 = cJSON_GetObjectItem(modules, elModule->string);
			char path[128];
			if (cJSON_HasObjectItem(elModule, "path"))
				strcpy(path, cJSON_GetStringValue2(elModule, "path"));
			else
				snprintf(path, sizeof(path), "/usr/local/modules/%s", elModule->string);
			snprintf(sz, sizeof(sz), "\
<Macro Macro_%s>\n\
	MyDongleCloudModule %s\n\
	Use Macro_Redirect %s\n\
	Header set Content-Security-Policy \"frame-ancestors 'self' *:9400", elModule->string, elModule->string, elModule->string);
			fwrite(sz, strlen(sz), 1, pfM);
			jsonPrintArray(0, " ", " ", "app", fqdn, "", pfM);
			//jsonPrintArray(0, " ", " ", "mydonglecloud", fqdn, "", pfM);
			strcpy(sz, ";\"\n");
			fwrite(sz, strlen(sz), 1, pfM);
			if (cJSON_HasObjectItem(elModule, "rewriteRule")) {
				snprintf(sz, sizeof(sz), "\t%s\n", cJSON_GetStringValue2(elModule, "rewriteRule"));
				fwrite(sz, strlen(sz), 1, pfM);
			}
			if (cJSON_HasObjectItem(elModule2, "rewriteRule")) {
				snprintf(sz, sizeof(sz), "\t%s\n", cJSON_GetStringValue2(elModule2, "rewriteRule"));
				fwrite(sz, strlen(sz), 1, pfM);
			}

			cJSON *elEnabled = cJSON_GetObjectItem(elModule, "enabled");
			if (cJSON_HasObjectItem(elModule2, "enabled"))
				elEnabled = cJSON_GetObjectItem(elModule2, "enabled");
			if (cJSON_IsTrue(elEnabled)) {
				cJSON *elPermissions = cJSON_GetObjectItem(elModule, "permissions");
				if (cJSON_HasObjectItem(elModule2, "permissions"))
					elPermissions = cJSON_GetObjectItem(elModule2, "permissions");

				if (cJSON_HasObjectItem(elModule, "addConfig")) {
					snprintf(sz, sizeof(sz), "\t%s\n", cJSON_GetStringValue2(elModule, "addConfig"));
					fwrite(sz, strlen(sz), 1, pfM);
				}
				if (cJSON_HasObjectItem(elModule2, "addConfig")) {
					snprintf(sz, sizeof(sz), "\t%s\n", cJSON_GetStringValue2(elModule2, "addConfig"));
					fwrite(sz, strlen(sz), 1, pfM);
				}

				int dirProxy = 0;
				if (cJSON_HasObjectItem(elModule, "reverseProxy")) {
					cJSON *elReverseProxy = cJSON_GetObjectItem(elModule, "reverseProxy");
					for (int j = 0; j < cJSON_GetArraySize(elReverseProxy); j++) {
						cJSON *elReverseProxy_ = cJSON_GetArrayItem(elReverseProxy, j);
						char *type_ = cJSON_GetStringValue2(elReverseProxy_, "type");
						char *path_ = cJSON_GetStringValue2(elReverseProxy_, "path");
						int reversePort = (int)cJSON_GetNumberValue(cJSON_GetObjectItem(elReverseProxy_, "port"));
						if (strcmp(type_, "http") == 0) {
							snprintf(sz, sizeof(sz), "\tProxyPass %s http://localhost:%d%s\n\tProxyPassReverse %s http://localhost:%d%s\n", path_, reversePort, path_, path_, reversePort, path_);
							dirProxy = 1;
						}
						else if (strcmp(type_, "ws") == 0)
							snprintf(sz, sizeof(sz), "\tRewriteCond %%{HTTP:Upgrade} websocket [NC]\n\tRewriteCond %%{HTTP:Connection} upgrade [NC]\n\tRewriteRule ^%s(.*) ws://localhost:%d%s$1 [P,L]\n", path_, reversePort, path_);
						fwrite(sz, strlen(sz), 1, pfM);
					}
				}
				if (dirProxy == 1) {
					strcpy(sz, "\t<Proxy *>\n");
					fwrite(sz, strlen(sz), 1, pfM);
				} else {
					snprintf(sz, sizeof(sz), "\tDocumentRoot %s\n\t<Directory %s>\n", path, path);
					fwrite(sz, strlen(sz), 1, pfM);
				}
				if (cJSON_HasObjectItem(elModule, "addLineInDirectory")) {
					snprintf(sz, sizeof(sz), "\t\t%s\n", cJSON_GetStringValue2(elModule, "addLineInDirectory"));
					fwrite(sz, strlen(sz), 1, pfM);
				}
				if (cJSON_HasObjectItem(elModule2, "addLineInDirectory")) {
					snprintf(sz, sizeof(sz), "\t\t%s\n", cJSON_GetStringValue2(elModule2, "addLineInDirectory"));
					fwrite(sz, strlen(sz), 1, pfM);
				}
				writePermissions(elPermissions, elLocalRanges, pfM);
				if (cJSON_HasObjectItem(elModule2, "DirectoryIndex"))
					writeDirectoryIndex(cJSON_GetStringValue2(elModule2, "DirectoryIndex"), pfM);
				else if (cJSON_HasObjectItem(elModule, "DirectoryIndex"))
					writeDirectoryIndex(cJSON_GetStringValue2(elModule, "DirectoryIndex"), pfM);
				if (cJSON_HasObjectItem(elModule2, "FollowSymLinks"))
					writeSymlinks(cJSON_IsTrue(cJSON_GetObjectItem(elModule2, "FollowSymLinks")), pfM);
				else if (cJSON_GetObjectItem(elModule, "FollowSymLinks"))
					writeSymlinks(cJSON_IsTrue(cJSON_GetObjectItem(elModule, "FollowSymLinks")), pfM);
				if (cJSON_HasObjectItem(elModule2, "Indexes"))
					writeIndexes(cJSON_IsTrue(cJSON_GetObjectItem(elModule2, "Indexes")), pfM);
				else if (cJSON_GetObjectItem(elModule, "Indexes"))
					writeIndexes(cJSON_IsTrue(cJSON_GetObjectItem(elModule, "Indexes")), pfM);

				if (dirProxy)
					strcpy(sz, "\t</Proxy>\n");
				else
					strcpy(sz, "\t</Directory>\n");
				fwrite(sz, strlen(sz), 1, pfM);

				if (strcmp(elModule->string, "apache2") == 0 || strcmp(elModule->string, "mydonglecloud") == 0) {
					strcpy(sz, "\tUse Macro_Rewrite\n");
					fwrite(sz, strlen(sz), 1, pfM);
				}
				if (strcmp(elModule->string, "apache2") == 0) {
					strcpy(sz, "\
	ErrorDocument 404 /_app_/notpresent.php\n\
	ErrorDocument 500 /_app_/error.php\n");
					fwrite(sz, strlen(sz), 1, pfM);
				}
			} else {
				snprintf(sz, sizeof(sz), "\
	RewriteCond %%{REQUEST_URI} !^/_app_/disabled.php$\n\
	RewriteRule ^/.*$ /_app_/disabled.php?m=%s [PT,L]\n\n", elModule->string);
				fwrite(sz, strlen(sz), 1, pfM);
			}
			writeLog(elModule->string, pfM);
			strcpy(sz, "</Macro>\n");
			fwrite(sz, strlen(sz), 1, pfM);

			int localPort = (int)cJSON_GetNumberValue(cJSON_GetObjectItem(elModule, "localPort"));
			sprintf(sz, "Listen %d\n", localPort);
			fwrite(sz, strlen(sz), 1, pfP);
			snprintf(sz, sizeof(sz), "<VirtualHost *:%d>\n\tUse Macro_%s\n</VirtualHost>\n", localPort, elModule->string);
			fwrite(sz, strlen(sz), 1, pfM);

			strcpy(sz, "<VirtualHost *:80>\n");
			fwrite(sz, strlen(sz), 1, pfM);
			fillServer(1, elModule, elModule2, fqdn, pfM);
			snprintf(sz, sizeof(sz), "\tUse Macro_%s\n</VirtualHost>\n", elModule->string);
			fwrite(sz, strlen(sz), 1, pfM);

			strcpy(sz, "<IfModule mod_ssl.c>\n\t<VirtualHost *:443>\n");
			fwrite(sz, strlen(sz), 1, pfM);
			fillServer(2, elModule, elModule2, fqdn, pfM);
			snprintf(sz, sizeof(sz), "\t\tUse Macro_%s\n\t\tUse Macro_SSL\n\t</VirtualHost>\n</IfModule>\n", elModule->string);
			fwrite(sz, strlen(sz), 1, pfM);

			strcpy(sz, "\n\n");
			fwrite(sz, strlen(sz), 1, pfM);
		}
	}
	fclose(pfP);
	fclose(pfM);
}
