"%d warnings","","","","","","","","","",
"A long press on the top left button will sleep the screen and the led. The dongle will still function.","","","","","","","","","",
"Are you sure to shutdown the dongle?","","","","","","","","","",
"Back","Retour","","","","","","","","",
"Bye now!","","","","","","","","","",
"CPU","","","","","","","","","",
"Cancel","","","","","","","","","",
"Cancel the code\nif you didn't request.\nExpires in %2ds","","","","","","","","","",
"Cancel the code\nif you didn't request.\nExpires in %dm %2ds","","","","","","","","","",
"Disk","","","","","","","","","",
"Done","","","","","","","","","",
"Exit","","","","","","","","","",
"Health","","","","","","","","","",
"Hide","","","","","","","","","",
"It's recommended to properly shutdown the device with a long press on the top right button.","","","","","","","","","",
"Mem","","","","","","","","","",
"New module are constantly added. Check on the app regularly.","","","","","","","","","",
"Next","","","","","","","","","",
"No","","","","","","","","","",
"Not connected","","","","","","","","","",
"OK","","","","","","","","","",
"Port https (443)","","","","","","","","","",
"Port imaps (993)","","","","","","","","","",
"Port mail (25)","","","","","","","","","",
"Port pop3s (995)","","","","","","","","","",
"Port smtps (465)","","","","","","","","","",
"Press both bottom buttons at the same time for 10 seconds to reset and delete all the dongle data.","","","","","","","","","",
"Press long on the top buttons to turn off the screen or shutdown.","","","","","","","","","",
"Press the top right button to access the Setup qrcode. Communication will be over Bluetooth.","","","","","","","","","",
"Prev.","","","","","","","","","",
"Rot","","","","","","","","","",
"Rotation is not supported on the web demo.","","","","","","","","","",
"Setup","","","","","","","","","",
"Sleeping...","","","","","","","","","",
"Storage","","","","","","","","","",
"Tips","","","","","","","","","",
"Use the buttons (except OK) to rotate the screen.","","","","","","","","","",
"Welcome!","","","","","","","","","",
"Yes","","","","","","","","","",
"You can recover a bricked dongle with the recovery tool (available on Windows, Linux and Mac).","","","","","","","","","",
"Your code is","","","","","","","","","",
