"Action","Action","","","","","","","","",
"Back","Retour","","","","","","","","",
"Cancel","Annuler","","","","","","","","",
"Cancel the code\nif you didn't request.\nExpires in %2ds","Annuler le code si\npas votre demande\nExpire dans %2ds","","","","","","","","",
"Cancel the code\nif you didn't request.\nExpires in %dm %2ds","Annuler le code si\npas votre demande\nExpire dans %dm %2ds","","","","","","","","",
"Confirmation","Confirmation","","","","","","","","",
"Hide","Cacher","","","","","","","","",
"Home","Maison","","","","","","","","",
"Message","Message","","","","","","","","",
"No","Non","No","Não","Nein","No","Nee","否","番号","아니",
"OFF","OFF","","","","","","","","",
"OK","OK","OK","OK","OK","OK","Oké","好","OK","확인",
"Quiet","Silence","","","","","","","","",
"Report","Rapport","","","","","","","","",
"Rotate","Tourner","","","","","","","","",
"Rotate %d","Tourner %d","","","","","","","","",
"Welcome! press a button to start...","Bienvenue ! Pressez un bouton pour demarrer...","¡Bienvenido! Elige tu idioma y presiona Próximo","Bem-vinda! Escolha seu idioma e pressione Próximo","Herzlich willkommen! Wählen Sie Ihre Sprache und klicken Sie auf Weiter","Benvenuto! Scegli la tua lingua e premi Seguente","Welkom! Selecteer uw taal en druk op Volgende","欢迎！选择您的语言，然后按下一个","ようこそ！言語を選択 して[次へ]を押してください","어서 오십시오! 언어를 선택하고 다음을 누릅니다",
"Yes","Oui","Si","Sim","Ja","Sì","Ja","是","はい","예",
"Your code is:","Votre code est :","","","","","","","","",
